/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/profielservice/v1/contactgegeven/{identificatieType}/{identificatieNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update contactgegeven van een partij
         * @description Werk type, waarde en scope van een contactgegeven bij. Identificatie kan niet aangepast worden.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: components["schemas"]["IdentificatieType"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ContactgegevenUpdateRequest"];
                };
            };
            responses: {
                /** @description Contactgegeven succesvol bijgewerkt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Contactgegeven of partij niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Toevoegen nieuwe contactgegeven voor een partij
         * @description Voegt een nieuwe contactgegeven toe. Creëert automatisch ontbrekende partijen.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: components["schemas"]["IdentificatieType"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ContactgegevenRequest"];
                };
            };
            responses: {
                /** @description Contactgegeven succesvol toegevoegd */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profielservice/v1/contactgegeven/{identificatieType}/{identificatieNummer}/{contactgegevenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Verwijder contactgegeven van een partij
         * @description Verwijdert een contactgegeven volledig
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    contactgegevenId: number;
                    identificatieNummer: string;
                    identificatieType: components["schemas"]["IdentificatieType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Contactgegeven succesvol verwijderd */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Contactgegeven of partij niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profielservice/v1/dienstverlener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Dienstverlener */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DienstverlenerRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profielservice/v1/dienstverlener/{DienstverlenerNaam}/diensten": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Voegt een dienst toe aan een dienstverlener
         * @description Voegt een nieuwe dienst toe met beschrijving
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    DienstverlenerNaam: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DienstRequest"];
                };
            };
            responses: {
                /** @description Dienst succesvol toegevoegd */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Dienstverlener niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profielservice/v1/dienstverlener/{naam}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Diensten Dienstverlener */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    naam: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profielservice/v1/emailverificatie": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Email Verificatie */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EmailVerificatieRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profielservice/v1/voorkeur/{identificatieType}/{identificatieNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update voorkeur van een partij
         * @description Werk type, waarde en scope van een voorkeur bij. Identificatie kan niet aangepast worden.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: components["schemas"]["IdentificatieType"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VoorkeurUpdateRequest"];
                };
            };
            responses: {
                /** @description Voorkeur succesvol bijgewerkt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Voorkeur of partij niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * Toevoegen nieuwe voorkeur voor een partij
         * @description Voegt een nieuwe voorkeur toe. Creëert automatisch ontbrekende partijen.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: components["schemas"]["IdentificatieType"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VoorkeurRequest"];
                };
            };
            responses: {
                /** @description Voorkeur succesvol toegevoegd */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profielservice/v1/voorkeur/{identificatieType}/{identificatieNummer}/{voorkeurId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Verwijder voorkeur van een partij
         * @description Verwijdert een voorkeur volledig
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: components["schemas"]["IdentificatieType"];
                    voorkeurId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Voorkeur succesvol verwijderd */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Voorkeur of partij niet gevonden */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profielservice/v1/{identificatieType}/{identificatieNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ophalen profiel van een partij
         * @description Haalt het profiel op van een partij
         */
        get: {
            parameters: {
                query?: {
                    dienstBeschrijving?: string;
                    dienstverlener?: string;
                    oin?: string;
                };
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: components["schemas"]["IdentificatieType"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Partij succesvol opgehaald */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PartijResponse"];
                    };
                };
                /** @description Partij niet gevonden of is verwijderd */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Request object voor het toevoegen van een dienst aan een dienstverlener */
        DienstRequest: {
            beschrijving: string;
        };
        DienstResponse: {
            /** Format: int64 */
            id?: number;
            beschrijving?: string;
        };
        /** @enum {string} */
        ContactType: "Email" | "Telefoonnummer" | "Adres";
        /** @enum {string} */
        Taal: "Nederlands" | "Engels" | "Fries" | "Papiamento" | "Papiamentu";
        /** @description Scope waarop een contactgegeven of voorkeur betrekking heeft */
        ScopeRequest: {
            scopeIdentificatieType?: components["schemas"]["IdentificatieType"];
            scopeIdentificatieNummer?: string;
            /** Format: int64 */
            dienstId?: number;
        };
        /** @description Scope waarop een contactgegeven of voorkeur betrekking heeft */
        ScopeResponse: {
            partij?: components["schemas"]["IdentificatieResponse"];
            dienst?: components["schemas"]["DienstResponse"];
        };
        /** @description Request object voor het toevoegen van een contactgegeven aan een partij */
        ContactgegevenRequest: {
            type: components["schemas"]["ContactType"];
            waarde: string;
            scope?: components["schemas"]["ScopeRequest"];
        };
        ContactgegevenResponse: {
            /** Format: int64 */
            id?: number;
            type?: components["schemas"]["ContactType"];
            waarde?: string;
            isGeverifieerd?: boolean;
            nogSteedsValide?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUpdated?: string;
            scope?: components["schemas"]["ScopeResponse"];
        };
        ContactgegevenUpdateRequest: {
            type: components["schemas"]["ContactType"];
            waarde: string;
            scope?: components["schemas"]["ScopeRequest"];
            /** Format: int64 */
            id?: number;
        };
        /** @description Request object voor het toevoegen van een dienstverlener */
        DienstverlenerRequest: {
            naam: string;
            oin: string;
        };
        /** @description Request object voor het verifiëren van een emailadres */
        EmailVerificatieRequest: {
            email: string;
            identificatieNummer: string;
            identificatieType: components["schemas"]["IdentificatieType"];
            verificatieCode: string;
        };
        IdentificatieResponse: {
            identificatieType?: components["schemas"]["IdentificatieType"];
            identificatieNummer?: string;
        };
        /** @enum {string} */
        IdentificatieType: "BSN" | "KVK" | "RSIN";
        /** @description Request object voor extra informatie meesturen bij van een Partij */
        PartijRequest: {
            dienstverlener?: string;
            dienstverlenerOin?: string;
            dienstBeschrijving?: string;
        };
        PartijResponse: {
            /** Format: int64 */
            partijId?: number;
            identificaties?: components["schemas"]["IdentificatieResponse"][];
            voorkeuren?: components["schemas"]["VoorkeurResponse"][];
            contactgegevens?: components["schemas"]["ContactgegevenResponse"][];
        };
        VoorkeurRequest: {
            voorkeurType: components["schemas"]["VoorkeurType"];
            waarde: string;
            scope?: components["schemas"]["ScopeRequest"];
        };
        VoorkeurResponse: {
            /** Format: int64 */
            id?: number;
            voorkeurType?: components["schemas"]["VoorkeurType"];
            waarde?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            lastUpdated?: string;
            scope?: components["schemas"]["ScopeResponse"];
        };
        /** @enum {string} */
        VoorkeurType: "WebsiteTaal" | "MagGebeldWorden" | "WebsiteThema" | "Aanhef";
        VoorkeurUpdateRequest: {
            voorkeurType: components["schemas"]["VoorkeurType"];
            waarde: string;
            scope?: components["schemas"]["ScopeRequest"];
            /** Format: int64 */
            id?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const contactTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ContactType"]> = ["Email", "Telefoonnummer", "Adres"];
export const taalValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Taal"]> = ["Nederlands", "Engels", "Fries", "Papiamento", "Papiamentu"];
export const identificatieTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["IdentificatieType"]> = ["BSN", "KVK", "RSIN"];
export const voorkeurTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["VoorkeurType"]> = ["WebsiteTaal", "MagGebeldWorden", "WebsiteThema", "Aanhef"];
export type operations = Record<string, never>;
