/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auditlogs/{kvkNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    ascending?: boolean;
                };
                header?: never;
                path: {
                    kvkNummer: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuditLogResponse"];
                        "application/json": components["schemas"]["AuditLogResponse"];
                        "text/json": components["schemas"]["AuditLogResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/generate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondernemingen/{kvkNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kvkNummer: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfielResponse"];
                        "application/json": components["schemas"]["ProfielResponse"];
                        "text/json": components["schemas"]["ProfielResponse"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: {
                    email?: string;
                };
                header?: never;
                path: {
                    kvkNummer: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfielResponse"];
                        "application/json": components["schemas"]["ProfielResponse"];
                        "text/json": components["schemas"]["ProfielResponse"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kvkNummer: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfielResponse"];
                        "application/json": components["schemas"]["ProfielResponse"];
                        "text/json": components["schemas"]["ProfielResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondernemingen/{kvkNummer}/{timestamp}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kvkNummer: string;
                    timestamp: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProfielResponse"];
                        "application/json": components["schemas"]["ProfielResponse"];
                        "text/json": components["schemas"]["ProfielResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondernemingen/EmailBekend/{kvkNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    kvkNummer: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": boolean;
                        "application/json": boolean;
                        "text/json": boolean;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ondernemingen/{kvkNummer}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: {
                    code?: string;
                };
                header?: never;
                path: {
                    kvkNummer: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Adres: {
            type?: string | null;
            indAfgeschermd?: string | null;
            volledigAdres?: string | null;
            straatnaam?: string | null;
            /** Format: int32 */
            huisnummer?: number;
            huisletter?: string | null;
            huisnummerToevoeging?: string | null;
            toevoegingAdres?: string | null;
            postcode?: string | null;
            /** Format: int32 */
            postbusnummer?: number;
            plaats?: string | null;
            straatHuisnummer?: string | null;
            postcodeWoonplaats?: string | null;
            regio?: string | null;
            land?: string | null;
            geoData?: components["schemas"]["GeoData"];
            additionalProperties?: {
                [key: string]: unknown;
            } | null;
        };
        AuditLogResponse: {
            OndernemingAuditLog: components["schemas"]["OndernemingAuditLog"][] | null;
        };
        Basisprofiel: {
            kvkNummer?: string | null;
            indNonMailing?: string | null;
            naam?: string | null;
            formeleRegistratiedatum?: string | null;
            materieleRegistratie?: components["schemas"]["MaterieleRegistratie"];
            /** Format: int32 */
            totaalWerkzamePersonen?: number;
            statutaireNaam?: string | null;
            handelsnamen?: components["schemas"]["Handelsnaam"][] | null;
            sbiActiviteiten?: components["schemas"]["SBIActiviteit"][] | null;
            _links?: {
                [key: string]: components["schemas"]["Link"];
            } | null;
            _embedded?: components["schemas"]["EmbeddedContainer"];
            additionalProperties?: {
                [key: string]: unknown;
            } | null;
        };
        /** @enum {string} */
        DienstType: "Alles" | "Financien" | "Personeelszaken" | "Anders";
        Eigenaar: {
            rsin?: string | null;
            rechtsvorm?: string | null;
            uitgebreideRechtsvorm?: string | null;
            adressen?: components["schemas"]["Adres"][] | null;
            websites?: string[] | null;
            _links?: {
                [key: string]: components["schemas"]["Link"];
            } | null;
            additionalProperties?: {
                [key: string]: unknown;
            } | null;
        };
        EmailModel: {
            email?: string | null;
            dienstType?: components["schemas"]["DienstType"];
        };
        EmbeddedContainer: {
            hoofdvestiging?: components["schemas"]["Vestiging"];
            eigenaar?: components["schemas"]["Eigenaar"];
            additionalProperties?: {
                [key: string]: unknown;
            } | null;
        };
        GeoData: {
            addresseerbaarObjectId?: string | null;
            nummerAanduidingId?: string | null;
            /** Format: double */
            gpsLatitude?: number;
            /** Format: double */
            gpsLongitude?: number;
            /** Format: double */
            rijksdriehoekX?: number;
            /** Format: double */
            rijksdriehoekY?: number;
            /** Format: double */
            rijksdriehoekZ?: number;
            additionalProperties?: {
                [key: string]: unknown;
            } | null;
        };
        Handelsnaam: {
            naam?: string | null;
            /** Format: int32 */
            volgorde?: number;
            additionalProperties?: {
                [key: string]: unknown;
            } | null;
        };
        Link: {
            href?: string | null;
            hreflang?: string | null;
            title?: string | null;
            type?: string | null;
            deprecation?: string | null;
            profile?: string | null;
            name?: string | null;
            templated?: boolean;
            additionalProperties?: {
                [key: string]: unknown;
            } | null;
        };
        MaterieleRegistratie: {
            datumAanvang?: string | null;
            datumEinde?: string | null;
            additionalProperties?: {
                [key: string]: unknown;
            } | null;
        };
        Onderneming: {
            kvkNummer?: string | null;
            email?: string | null;
            emailVerified?: boolean;
            emails?: components["schemas"]["EmailModel"][] | null;
        };
        OndernemingAuditLog: {
            /** Format: int32 */
            ondernemingId?: number;
            action?: string | null;
            field?: string | null;
            oldValue?: string | null;
            newValue?: string | null;
            performedBy?: string | null;
            /** Format: date-time */
            performedAt?: string;
        };
        ProfielResponse: {
            Onderneming: components["schemas"]["Onderneming"];
            KvkProfiel: components["schemas"]["Basisprofiel"];
            UwvProfiel?: unknown;
        };
        SBIActiviteit: {
            sbiCode?: string | null;
            sbiOmschrijving?: string | null;
            indHoofdactiviteit?: string | null;
            additionalProperties?: {
                [key: string]: unknown;
            } | null;
        };
        Vestiging: {
            vestigingsnummer?: string | null;
            kvkNummer?: string | null;
            rsin?: string | null;
            indNonMailing?: string | null;
            formeleRegistratiedatum?: string | null;
            materieleRegistratie?: components["schemas"]["MaterieleRegistratie"];
            statutaireNaam?: string | null;
            eersteHandelsnaam?: string | null;
            indHoofdvestiging?: string | null;
            indCommercieleVestiging?: string | null;
            /** Format: int32 */
            voltijdWerkzamePersonen?: number;
            /** Format: int32 */
            totaalWerkzamePersonen?: number;
            /** Format: int32 */
            deeltijdWerkzamePersonen?: number;
            handelsnamen?: components["schemas"]["Handelsnaam"][] | null;
            adressen?: components["schemas"]["Adres"][] | null;
            websites?: string[] | null;
            sbiActiviteiten?: components["schemas"]["SBIActiviteit"][] | null;
            _links?: {
                [key: string]: components["schemas"]["Link"];
            } | null;
            additionalProperties?: {
                [key: string]: unknown;
            } | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
