/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/actualiteitenservice/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lijst artikelen
         * @description Haalt een gefilterde lijst artikelen op. Service houdt een enriched cache met alle artikelen (inclusief subjects uit het detail-endpoint); filteren gebeurt in-memory.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    search?: string;
                    subject?: string[];
                    type?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArticlesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/berichten/{identificatieType}/{identificatieNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Berichten voor een partij
         * @description Leest de postcode-voorkeuren van de partij uit, haalt per postcode bekendmakingen op uit de SRU (gecached), en retourneert een gededupliceerde, op datum gesorteerde lijst.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SruPublicatie"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/ingestion-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Status van bronnen
         * @description Laatste succesvolle refresh per bron. Portaal gebruikt dit voor de 'laatst bijgewerkt' indicator.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/subsidies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lijst subsidies
         * @description Haalt een gefilterde lijst subsidies op. Service houdt een enriched cache met alle subsidies (inclusief subjects/regions uit het detail-endpoint); filteren gebeurt in-memory.
         */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    region?: string[];
                    subject?: string[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubsidiesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/voorkeuren/favoriet/{identificatieType}/{identificatieNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voeg favoriet artikel toe */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["FavorietRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/voorkeuren/favoriet/{identificatieType}/{identificatieNummer}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Verwijder favoriet artikel */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    identificatieNummer: string;
                    identificatieType: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/voorkeuren/onderwerp/{identificatieType}/{identificatieNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voeg onderwerp-voorkeur toe */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OnderwerpRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/voorkeuren/onderwerp/{identificatieType}/{identificatieNummer}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Verwijder onderwerp-voorkeur */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    identificatieNummer: string;
                    identificatieType: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/voorkeuren/postcode/{identificatieType}/{identificatieNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Voeg postcode-voorkeur toe */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PostcodeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/voorkeuren/postcode/{identificatieType}/{identificatieNummer}/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Verwijder postcode-voorkeur */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                    identificatieNummer: string;
                    identificatieType: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": unknown;
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/actualiteitenservice/v1/voorkeuren/{identificatieType}/{identificatieNummer}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alle voorkeuren voor een partij */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    identificatieNummer: string;
                    identificatieType: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VoorkeurenResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ArticlesResponse: {
            articles?: components["schemas"]["EnrichedArticle"][];
            /** Format: int32 */
            total?: number;
        };
        EnrichedArticle: {
            identifier?: string;
            headLine?: string;
            additionalType?: string;
            url?: string;
            dateModified?: string;
            subjects?: string[];
        };
        EnrichedSubsidie: {
            identifier?: string;
            title?: string;
            url?: string;
            dateModified?: string;
            subjects?: string[];
            regions?: string[];
        };
        FavorietItem: {
            /** Format: int64 */
            id?: number;
            articleId?: string;
            articleType?: string;
            addedAt?: components["schemas"]["Instant"];
        };
        FavorietRequest: {
            articleId?: string;
            articleType?: string;
        };
        /**
         * Format: date-time
         * @example 2022-03-10T16:15:50Z
         */
        Instant: string;
        OnderwerpItem: {
            /** Format: int64 */
            id?: number;
            onderwerp?: string;
        };
        OnderwerpRequest: {
            onderwerp?: string;
        };
        PostcodeItem: {
            /** Format: int64 */
            id?: number;
            postcode?: string;
        };
        PostcodeRequest: {
            postcode?: string;
        };
        SruPublicatie: {
            id?: string;
            title?: string;
            type?: string;
            creator?: string;
            modified?: string;
            abstract?: string;
            preferredUrl?: string;
            bronUrl?: string;
            postcodes?: string[];
            productArea?: string;
            audience?: string;
            subject?: string;
            publicatienaam?: string;
        };
        SubsidiesResponse: {
            subsidies?: components["schemas"]["EnrichedSubsidie"][];
            /** Format: int32 */
            total?: number;
        };
        VoorkeurenResponse: {
            postcodes?: components["schemas"]["PostcodeItem"][];
            onderwerpen?: components["schemas"]["OnderwerpItem"][];
            favorieten?: components["schemas"]["FavorietItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
