/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter articles */
        get: {
            parameters: {
                query?: {
                    /** @description Filter on a search string. */
                    search?: string;
                    /** @description Filter on one or multiple article types (a.k.a. additionalType). These are supported types:
                     *     artikel-nl, regel-nl, wetswijziging-nl, subsidie-nl, page-nl, video. */
                    type?: string[];
                    /** @description Filter on one or multiple subjects. */
                    subject?: string[];
                    /** @description Paging offset filter. Default value is 0 when not specified. */
                    offset?: number;
                    /** @description Paging limit filter. Default value is 20 when not specified. Max value is 200. */
                    limit?: number;
                    /** @description Sort order. Articles can be ordered by two attributes: dateModified and additionalType. The
                     *     following order tokens represent the order filtering of those two attributes in ascending and descending orders:
                     *     modified:desc, modified:asc, modified (same as modified:asc), type:desc, type:asc, type (same as type:asc). Example:
                     *     order=modified:desc,type:desc */
                    order?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArticlesContract"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter articles */
        get: {
            parameters: {
                query?: {
                    /** @description Filter on a search string. */
                    search?: string;
                    /** @description Filter on one or multiple article types (a.k.a. additionalType). These are supported types:
                     *     artikel-nl, regel-nl, wetswijziging-nl, subsidie-nl, page-nl, video. */
                    type?: string[];
                    /** @description Filter on one or multiple subjects. */
                    subject?: string[];
                    /** @description Paging offset filter. Default value is 0 when not specified. */
                    offset?: number;
                    /** @description Paging limit filter. Default value is 20 when not specified. Max value is 200. */
                    limit?: number;
                    /** @description Sort order. Articles can be ordered by two attributes: dateModified and additionalType. The
                     *     following order tokens represent the order filtering of those two attributes in ascending and descending orders:
                     *     modified:desc, modified:asc, modified (same as modified:asc), type:desc, type:asc, type (same as type:asc). Example:
                     *     order=modified:desc,type:desc */
                    order?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArticlesContract"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get article by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of article. ID has a numerical value. Example: 274863 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArticleContract"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get article by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of article. ID has a numerical value. Example: 274863 */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ArticleContract"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter events */
        get: {
            parameters: {
                query?: {
                    /** @description Filter on one or multiple regions/provinces (case-insensitive). Examples: noord-holland, limburg. */
                    regions?: string[];
                    /** @description Filter on location (city) of event venues (case-insensitive). Location filter overrides regions filter when both are
                     *     specified while the location (city) is situated outside of the specified regions (provinces). Examples:
                     *     amsterdam, utrecht. */
                    location?: string;
                    /** @description Filter on address of event venues. */
                    address?: string;
                    /** @description Filter on postal code of event venues. */
                    postalCode?: string;
                    /** @description Filter on one or multiple subjects (case-insensitive). Examples: bedrijf starten, personeel. */
                    subjects?: string[];
                    /** @description Filter on period. Supported values: comingweek, comingmonth, comingyear (default). */
                    period?: string;
                    /** @description Paging offset filter. Default value is 0 when not specified. */
                    offset?: number;
                    /** @description Paging limit filter. Default value is 20 when not specified. Max value is 200. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventsContract"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter events */
        get: {
            parameters: {
                query?: {
                    /** @description Filter on one or multiple regions/provinces (case-insensitive). Examples: noord-holland, limburg. */
                    regions?: string[];
                    /** @description Filter on location (city) of event venues (case-insensitive). Location filter overrides regions filter when both are
                     *     specified while the location (city) is situated outside of the specified regions (provinces). Examples:
                     *     amsterdam, utrecht. */
                    location?: string;
                    /** @description Filter on address of event venues. */
                    address?: string;
                    /** @description Filter on postal code of event venues. */
                    postalCode?: string;
                    /** @description Filter on one or multiple subjects (case-insensitive). Examples: bedrijf starten, personeel. */
                    subjects?: string[];
                    /** @description Filter on period. Supported values: comingweek, comingmonth, comingyear (default). */
                    period?: string;
                    /** @description Paging offset filter. Default value is 0 when not specified. */
                    offset?: number;
                    /** @description Paging limit filter. Default value is 20 when not specified. Max value is 200. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventsContract"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get event by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of event. ID has a numerical value. Example: 394528. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventContract"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get event by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of event. ID has a numerical value. Example: 394528. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EventContract"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subsidies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter subsidies */
        get: {
            parameters: {
                query?: {
                    /** @description Filter on one or multiple subjects (case-insensitive). Examples: agrosector, internationaal
                     *     ondernemen. */
                    subjects?: string[];
                    /** @description Filter on one or multiple regions/provinces (case-insensitive). Examples: noord-holland,
                     *     zuid-holland. */
                    regions?: string[];
                    /** @description Filter on regulation type (case-insensitive). Examples: krediet, subsidie. */
                    regulationType?: string;
                    /** @description Paging offset filter. Default value is 0 when not specified. */
                    offset?: number;
                    /** @description Paging limit filter. Default value is 20 when not specified. Max value is 200. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubsidiesContract"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subsidies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter subsidies */
        get: {
            parameters: {
                query?: {
                    /** @description Filter on one or multiple subjects (case-insensitive). Examples: agrosector, internationaal
                     *     ondernemen. */
                    subjects?: string[];
                    /** @description Filter on one or multiple regions/provinces (case-insensitive). Examples: noord-holland,
                     *     zuid-holland. */
                    regions?: string[];
                    /** @description Filter on regulation type (case-insensitive). Examples: krediet, subsidie. */
                    regulationType?: string;
                    /** @description Paging offset filter. Default value is 0 when not specified. */
                    offset?: number;
                    /** @description Paging limit filter. Default value is 20 when not specified. Max value is 200. */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubsidiesContract"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/subsidies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subsidy by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of subsidy. ID has a numerical value. Example: 275610. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubsidieContract"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/subsidies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subsidy by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of subsidy. ID has a numerical value. Example: 275610. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SubsidieContract"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all themes */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ThemesContract"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get theme by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of theme. ID has a numerical value. Example: 270107. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ThemeContract"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes/{id}/subjectsview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get theme by ID (articles grouped by subject) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description ID of theme. ID has a numerical value. Example: 270107. */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ThemeSubjectsContract"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/themes/featuredarticles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all themes with their featured articles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ThemesWithFeaturedArticleContract"];
                    };
                };
                /** @description Server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system/version/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Represents the datacontract of an article. */
        ArticleContract: {
            /** @description Article title. */
            headLine?: string | null;
            /** @description Article short description. */
            about?: string | null;
            /** @description Article type (a.k.a. additionalType). Article types include: artikel-nl, regel-nl, subsidie-nl,
             *     wetswijziging-nl, video. */
            additionalType?: string | null;
            /** @description Article content body (HTML). */
            articleBody?: string | null;
            /** @description Article URL. */
            url?: string | null;
            /** @description Article meta keywords. */
            keywords?: string[] | null;
            /** @description Article authors. Note: field naming of 'author' is singular, but author field contains an array of authors. */
            author?: components["schemas"]["Author"][] | null;
            publisher?: components["schemas"]["Author"];
            /** @description List of other articles that are related (referenced) to the same article. */
            isPartOf?: components["schemas"]["PartItem"][] | null;
            /** @description Related articles. */
            hasPart?: components["schemas"]["PartItem"][] | null;
            /** @description Subjects */
            subjects?: string[] | null;
            contact?: components["schemas"]["Contact"];
            /** @description Last modified date. */
            dateModified?: string | null;
            /** @description Creation date. */
            dateCreated?: string | null;
            /** @description Last published date. */
            datePublished?: string | null;
            /** @description Locale. */
            readonly inLanguage?: string | null;
            /** @description Article ID */
            identifier?: string | null;
        };
        /** @description Represents an article summary. */
        ArticleSummary: {
            /** @description Article title. */
            headLine?: string | null;
            /** @description Article type (a.k.a. additionalType). Article types include: artikel-nl, regel-nl, subsidie-nl,
             *     wetswijziging-nl, video. */
            additionalType?: string | null;
            /** @description Last modified date. */
            dateModified?: string | null;
            /** @description Article URL. */
            url?: string | null;
            /** @description Article ID. */
            identifier?: string | null;
        };
        /** @description Represents the datacontract of a list of article summaries. */
        ArticlesContract: {
            /** @description List of article summaries. */
            articles?: components["schemas"]["ArticleSummary"][] | null;
            pagination?: components["schemas"]["PagingInfo"];
        };
        /** @description Represent a content author. */
        Author: {
            /** @description Author name. */
            name?: string | null;
            /** @description Author website. */
            url?: string | null;
            /** @description Author logo. */
            logo?: string | null;
            /**
             * @description Author payoff.
             * @example Eén antwoord van de overheid
             */
            payoff?: string | null;
        };
        /** @description Represents contact information. */
        Contact: {
            /** @description Contact name. */
            title?: string | null;
            /** @description Contact e-mail. */
            email?: string | null;
            /** @description Contact twitter handle. */
            twitter?: string | null;
            /** @description Contact phones information. */
            phones?: components["schemas"]["ContactPhone"][] | null;
            /** @description Contact links. */
            links?: components["schemas"]["ContactLink"][] | null;
            /** @description Contact forum. */
            forums?: components["schemas"]["ContactLink"][] | null;
        };
        ContactLink: {
            /** @description Contact link title. */
            title?: string | null;
            /** @description Contact link description. */
            description?: string | null;
            /** @description Contact link URL. */
            url?: string | null;
        };
        ContactPhone: {
            /** @description Contact name. */
            title?: string | null;
            /** @description Contact description. */
            description?: string | null;
            /** @description Contact telephone number. */
            phone?: string | null;
        };
        /** @description Represents the datacontract of an event. */
        EventContract: {
            /** @description Event name. */
            name?: string | null;
            /** @description Event short description. */
            description?: string | null;
            /** @description Event content body (HTML). */
            content?: string | null;
            /** @description Event subjects. */
            subjects?: string[] | null;
            /** @description Event URL. */
            url?: string | null;
            /** @description Admission fee statement. */
            rate?: string | null;
            /** @description Event duration. */
            duration?: string | null;
            /** @description Event organizers. Note: field naming of 'organizer' is singular, but organizer field contains an array of arganizers. */
            organizer?: string[] | null;
            /** @description Locale. */
            readonly inLanguage?: string | null;
            /** @description List of event venues. */
            venues?: components["schemas"]["EventVenue"][] | null;
            /** @description Event ID. */
            identifier?: string | null;
        };
        /** @description Represents an event summary. */
        EventSummary: {
            /** @description Event name. */
            name?: string | null;
            /** @description Event short description. */
            description?: string | null;
            /** @description Event subjects. */
            subjects?: string[] | null;
            /** @description Admission fee statement. */
            rate?: string | null;
            /** @description Event duration. */
            duration?: string | null;
            /** @description List of event venues. */
            venues?: components["schemas"]["EventVenueSummary"][] | null;
            /** @description Event ID. */
            identifier?: string | null;
        };
        /** @description Represents the location where an event takes place. */
        EventVenue: {
            /** @description Venue name. */
            name?: string | null;
            /**
             * Format: date-time
             * @description Event start date and time.
             */
            startDate?: string;
            /**
             * Format: date-time
             * @description Event end date and time.
             */
            endDate?: string;
            /** @description Venue location (city). */
            location?: string | null;
            /** @description Venue address. */
            address?: string | null;
            /** @description Venue postal code. */
            postalCode?: string | null;
            /** @description Venue website. */
            url?: string | null;
            /** @description Registration URL. */
            registrationUrl?: string | null;
            /** @description Venue location on Google Maps. */
            map?: string | null;
        };
        /** @description Represents a summary of an event venue. */
        EventVenueSummary: {
            /** @description Venue location (city). */
            location?: string | null;
            /** @description Venue website. */
            url?: string | null;
            /** @description Event start date and time. */
            startDate?: string | null;
            /** @description Event end date and time. */
            endDate?: string | null;
        };
        /** @description Represents the datacontract of a list of event summaries. */
        EventsContract: {
            /** @description List of event summaries. */
            events?: components["schemas"]["EventSummary"][] | null;
            pagination?: components["schemas"]["PagingInfo"];
        };
        /** @description Represents pagination data of a result list. */
        PagingInfo: {
            /**
             * Format: int32
             * @description Pagination offset.
             */
            offset?: number;
            /**
             * Format: int32
             * @description Pagination limit.
             */
            limit?: number;
            /**
             * Format: int32
             * @description Pagination number of returned result.
             */
            returned?: number;
            /**
             * Format: int32
             * @description Pagination total number of result.
             */
            total?: number;
        };
        /** @description Represents a related article that is referenced inside the .hasPart or .isPartOf field of an article. */
        PartItem: {
            /** @description Part item type. (A part type describes the relation of a part item with its containting article). Part types include: further-info, parent,
             *     answer, related, external, legislation, amendment. */
            partType?: string | null;
            /** @description Article type (a.k.a. additionalType). Article types include: artikel-nl, regel-nl, subsidie-nl, wetswijziging-nl, video. */
            additionalType?: string | null;
            /** @description Part item (article) ID. */
            identifier?: string | null;
            /** @description Parent item (article) title. */
            headLine?: string | null;
            /** @description Part item (article) URL. */
            url?: string | null;
        };
        /** @description Represents the datacontract of a subsidy. */
        SubsidieContract: {
            /** @description Subsidy title. */
            title?: string | null;
            /** @description Subsidy content body (HTML). */
            content?: string | null;
            /** @description Subsidy short description. */
            description?: string | null;
            /** @description Subsidy URL. */
            url?: string | null;
            /** @description Subsidy subjects. */
            subjects?: string[] | null;
            /** @description Subsidy applicable regions. */
            regions?: string[] | null;
            /**
             * @description Regulation type.
             * @example subsidie, prijs, krediet, fiscale stimuleringsmaatregel.
             */
            regulationType?: string | null;
            /** @description Last modified date. */
            dateModified?: string | null;
            /** @description Creation date. */
            dateCreated?: string | null;
            /** @description Publish date. */
            datePublished?: string | null;
            /** @description Locale. */
            readonly inLanguage?: string | null;
            /** @description Subsidy ID. */
            identifier?: string | null;
        };
        /** @description Represents a summary of a subsidy. */
        SubsidieSummary: {
            /** @description Subsidy title. */
            title?: string | null;
            /** @description Subsidy URL. */
            url?: string | null;
            /** @description Subsidy ID. */
            identifier?: string | null;
        };
        /** @description Represents the datacontract of a list of subsidy summaries. */
        SubsidiesContract: {
            /** @description List of subsidy summaries. */
            subsidies?: components["schemas"]["SubsidieSummary"][] | null;
            pagination?: components["schemas"]["PagingInfo"];
        };
        /** @description Represents the datacontract of a theme. */
        ThemeContract: {
            /** @description Theme title. */
            headLine?: string | null;
            /** @description Theme URL. */
            url?: string | null;
            /** @description Last modified date. */
            dateModified?: string | null;
            /** @description List of related articles. */
            articles?: components["schemas"]["ArticleSummary"][] | null;
            /** @description List of related subsidies. */
            subsidies?: components["schemas"]["ArticleSummary"][] | null;
            /** @description List of related legislature. */
            legislature?: components["schemas"]["ArticleSummary"][] | null;
            /** @description Theme ID. */
            identifier?: string | null;
        };
        ThemeSubject: {
            /** @description Themesubject title. */
            title?: string | null;
            /** @description List of related articles. */
            articles?: components["schemas"]["ArticleSummary"][] | null;
        };
        /** @description Represents the datacontract of a subjecttheme. */
        ThemeSubjectsContract: {
            /** @description Theme title. */
            headLine?: string | null;
            /** @description Theme URL. */
            url?: string | null;
            /** @description Last modified date. */
            dateModified?: string | null;
            subjects?: components["schemas"]["ThemeSubject"][] | null;
            /** @description List of related subsidies. */
            subsidies?: components["schemas"]["ArticleSummary"][] | null;
            /** @description List of related legislature. */
            legislature?: components["schemas"]["ArticleSummary"][] | null;
            identifier?: string | null;
        };
        /** @description Represents a theme summary. */
        ThemeSummary: {
            /** @description Theme title. */
            headLine?: string | null;
            /** @description Theme URL. */
            url?: string | null;
            /** @description Last modified date. */
            dateModified?: string | null;
            /** @description Theme ID. */
            identifier?: string | null;
        };
        /** @description Represents a theme summary with featured articles. */
        ThemeSummaryWithFeaturedArticles: {
            /** @description Theme title. */
            headLine?: string | null;
            /** @description Theme URL. */
            url?: string | null;
            /** @description Last modified date. */
            dateModified?: string | null;
            /** @description Theme ID. */
            identifier?: string | null;
            /** @description List of featured articles. */
            articles?: components["schemas"]["ArticleSummary"][] | null;
        };
        /** @description Represents the datacontract of a list of theme summaries. */
        ThemesContract: {
            /** @description List of themes. */
            themes?: components["schemas"]["ThemeSummary"][] | null;
        };
        /** @description Represents a list of theme summaries with featured articles. */
        ThemesWithFeaturedArticleContract: {
            /** @description List of featured articles. */
            themes?: components["schemas"]["ThemeSummaryWithFeaturedArticles"][] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
