/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/uwv/meldingen": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ZwangerschapsverlofRequest"];
          "text/json": components["schemas"]["ZwangerschapsverlofRequest"];
          "application/*+json": components["schemas"]["ZwangerschapsverlofRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["UwvMeldingResponse"];
            "application/json": components["schemas"]["UwvMeldingResponse"];
            "text/json": components["schemas"]["UwvMeldingResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/uwv/meldingen/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["UwvMeldingResponse"];
            "application/json": components["schemas"]["UwvMeldingResponse"];
            "text/json": components["schemas"]["UwvMeldingResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/uwv/meldingen/{bedrijfsKvk}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          bedrijfsKvk: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["UwvMeldingResponse"][];
            "application/json": components["schemas"]["UwvMeldingResponse"][];
            "text/json": components["schemas"]["UwvMeldingResponse"][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/uwv/meldingen/{id}/opmerking": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateZwangerschapsverlofRequest"];
          "text/json": components["schemas"]["UpdateZwangerschapsverlofRequest"];
          "application/*+json": components["schemas"]["UpdateZwangerschapsverlofRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["UwvMeldingResponse"];
            "application/json": components["schemas"]["UwvMeldingResponse"];
            "text/json": components["schemas"]["UwvMeldingResponse"];
          };
        };
      };
    };
    trace?: never;
  };
  "/vng/aanvragen/parkeervergunning": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ParkeervergunningAanvraagRequest"];
          "text/json": components["schemas"]["ParkeervergunningAanvraagRequest"];
          "application/*+json": components["schemas"]["ParkeervergunningAanvraagRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["VngAanvraagResponse"];
            "application/json": components["schemas"]["VngAanvraagResponse"];
            "text/json": components["schemas"]["VngAanvraagResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/vng/aanvragen/subsidie": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["SubsidieAanvraagRequest"];
          "text/json": components["schemas"]["SubsidieAanvraagRequest"];
          "application/*+json": components["schemas"]["SubsidieAanvraagRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["VngAanvraagResponse"];
            "application/json": components["schemas"]["VngAanvraagResponse"];
            "text/json": components["schemas"]["VngAanvraagResponse"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/vng/aanvragen/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["VngAanvraagResponse"];
            "application/json": components["schemas"]["VngAanvraagResponse"];
            "text/json": components["schemas"]["VngAanvraagResponse"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/vng/aanvragen/bedrijf/{bedrijfsKvk}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          bedrijfsKvk: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "text/plain": components["schemas"]["VngAanvraagResponse"][];
            "application/json": components["schemas"]["VngAanvraagResponse"][];
            "text/json": components["schemas"]["VngAanvraagResponse"][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** @enum {string} */
    AanvraagStatusEnum:
      | "Ontvangen"
      | "InBehandeling"
      | "Goedgekeurd"
      | "Afgewezen";
    /** @enum {string} */
    AanvraagTypeEnum: "Parkeervergunning" | "Subsidie";
    ParkeervergunningAanvraagRequest: {
      bedrijfsKvk?: string;
      kenteken?: string;
      motivatie?: string | null;
      aanvragerEmail?: string | null;
    };
    SubsidieAanvraagRequest: {
      bedrijfsKvk?: string;
      subtype?: string;
      motivatie?: string | null;
      aanvragerEmail?: string | null;
    };
    UpdateZwangerschapsverlofRequest: {
      opmerking?: string;
    };
    UwvMeldingResponse: {
      referentie?: string;
      status?: string;
      /** Format: date-time */
      ontvangenOp?: string;
    };
    VngAanvraagResponse: {
      /** Format: uuid */
      referentie?: string;
      bedrijfsKvk?: string;
      type?: components["schemas"]["AanvraagTypeEnum"];
      subtype?: string | null;
      motivatie?: string | null;
      kenteken?: string | null;
      status?: components["schemas"]["AanvraagStatusEnum"];
      /** Format: date-time */
      timestamp?: string;
    };
    ZwangerschapsverlofRequest: {
      bsn: string;
      naam: string;
      /** Format: date-time */
      startDatum: string;
      /** Format: date-time */
      eindDatum: string;
      bedrijfsKvk: string;
      opmerking?: string | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
