/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/mijnoverheid/mijnorganisaties": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: {
      parameters: {
        query?: {
          /** @description Taal waarin de labels worden teruggegeven om meertaligheid van Mijn Overheid te kunnen ondersteunen. Default waarde is 'nl' */
          taal?: "nl" | "en";
          page?: number;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description request body met BSN voor het ophalen van lijst met Organisaties van de persoon */
      requestBody?: {
        content: {
          "application/json": components["schemas"]["MijnOverheidOrganisatiesRequestBody"];
        };
      };
      responses: {
        /** @description Lijst met organisaties */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["MijnOverheidOrganisatiesResponse"];
          };
        };
        /** @description Bad request */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    MijnOverheidOrganisatiesRequestBody: {
      bsn: components["schemas"]["BSN"];
    };
    /** @description Lijst met 0, 1 of meer organisaties waar de natuurlijk persoon een functie vervult */
    MijnOverheidOrganisatiesResponse: {
      metadata?: components["schemas"]["Metadata"];
      pagination?: components["schemas"]["Pagination"];
      /** @description Lijst van organisaties is per default gesorteerd op KVK nummer van laag naar hoog */
      organisaties?: components["schemas"]["Organisatie"][];
      itemAttributeLabels?: components["schemas"]["ItemAttributeLabels"];
    };
    /** @description Meertalige labels voor alle velden in de response */
    ItemAttributeLabels: {
      kvkNummer?: components["schemas"]["ItemAttributeObject"];
      administratieveHandelsnaam?: components["schemas"]["ItemAttributeObject"];
      rechtsvorm?: components["schemas"]["ItemAttributeObject"];
      functies?: components["schemas"]["ItemAttributeObject"];
      sbi?: components["schemas"]["ItemAttributeObject"];
      telefoonnummer?: components["schemas"]["ItemAttributeObject"];
      email?: components["schemas"]["ItemAttributeObject"];
      website?: components["schemas"]["ItemAttributeObject"];
    };
    /** @description Item attribuut object bestaat uit een label en een toelichting. Toelichting is een (i) op het scherm van Mijn Overheid in B1 taalniveau. Label is de tekst voor de waarde op het scherm in de juiste taal */
    ItemAttributeObject: {
      label?: string;
      toelichting?: string;
    };
    /** @description Burger Service Nummer */
    BSN: string;
    /** @description Metadata van het KVK Mijn Overheid Response bericht */
    Metadata: {
      /** @description Schema naam */
      $scheme?: string;
      /** @description Schema versie nummer */
      version?: string;
    };
    /** @description Pagina beschrijving */
    Pagination: {
      /** @description Huidige pagina */
      currentPage?: number;
      /** @description Aantal organisaties per pagina */
      itemsPerPage?: number;
      /** @description Organisatie item nummer op deze pagina */
      from?: number;
      /** @description Organisatie item nummer als laatste op deze pagina */
      to?: number;
      /** @description Totaal aantal organisaties */
      totalItems?: number;
      /** @description Laatste pagina nummer */
      lastPage?: number;
      /** @description Link naar de volgende pagina */
      next?: components["schemas"]["Href"];
      /** @description Link naar de vorige pagina */
      previous?: components["schemas"]["Href"];
    };
    Organisatie: {
      /** @description Het KVK nummer dat is toegekend aan een onderneming en/of rechtsvorm */
      kvkNummer: string;
      /** @description De naam van de organisatie, dit kan de statutaire naam, naam van de personenvennootschap of eerste handelsnaam van de hoofdvestiging zijn */
      administratieveHandelsnaam?: string;
      /** @description De rechtsvorm van de onderneming en/of rechtspersoon */
      rechtsvorm: string;
      functies: components["schemas"]["Functies"];
      sbi?: components["schemas"]["SBI"];
      /** @description Het telefoonnummer van de onderneming en/of rechtsvorm */
      telefoonnummer?: string;
      /** @description Emailadres van de onderneming en/of rechtsvorm */
      email?: string;
      /** @description Website van de onderneming en/of rechtsvorm */
      website?: string;
      /** URI links */
      _links: components["schemas"]["Links"];
    };
    Links: {
      /** @description Link naar de organisatie op Mijn KVK */
      self: {
        href: components["schemas"]["Href"];
        /** @description label tekst van de link naar de organisatie op Mijn KVK */
        linkText: string;
        /** @description Aria label voor de link t.b.v. accessability */
        ariaLabel: string;
      };
    };
    /** @description URI Link */
    Href: string;
    /** @description De SBI-code met omschrijving van de onderneming en/of rechtspersoon, de hoofdactiviteit van de organisatie */
    SBI: string;
    /** @description Een lijst met functies */
    Functies: components["schemas"]["Functie"][];
    /** @description De functie van de persoon voor de organisatie */
    Functie: string;
    /** @description Standaard error response object gebaseerd op https://tools.ietf.org/html/rfc7807. */
    ProblemDetails: {
      /** @description Error object omschrijving */
      title: string;
      /** @description URI of pad dat werd aangeroepen */
      instance: string;
      /** @description Ontwikkelaarsvriendelijke informatie met betrekking tot de error */
      detail?: string;
      /** @description URI conform RFC7807 */
      type?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
